CharacterLookupMVC/Models/Word.cs
namespace CharacterLookupMVC.Models
{
    public class Word
    {
        public char Character { get; set; }
        public Grades Grade { get; set; }
        public Semister Semister { get; set; }
        public string? Article { get; set; }

        public string GradeStr { get => EnumsConverter.GradeToString(Grade); }
        public string SemisterStr { get => EnumsConverter.SemisterToString(Semister); }

        public override string? ToString()
        {
            return $"{Character} 学于 {Grade} {Semister} {Article}";
        }
    }

    public enum Grades
    {
        One,
        Two,
        Three,
        Four,
        Five,
        Six
    }

    public enum Semister
    {
        First,
        Second
    }

    public static class EnumsConverter
    {
        static Dictionary<Grades, string> gradeDict = new Dictionary<Grades, string>()
        {
            [Grades.One] = "一年级",
            [Grades.Two] = "二年级",
            [Grades.Three] = "三年级",
            [Grades.Four] = "四年级",
            [Grades.Five] = "五年级",
            [Grades.Six] = "六年级"
        };

        public static string GradeToString(Grades grade)
        {
            return gradeDict[grade];
        }

        public static string SemisterToString(Semister semister)
        {
            if (semister == Semister.First)
            {
                return "上学期";
            }
            else
            {
                return "下学期";
            }
        }
    }
}

CharacterLookupMVC/Controllers/WordController.cs
using CharacterLookup.Models;
using CharacterLookupMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CharacterLookupMVC.Controllers
{
    [AllowAnonymous]
    public class WordController : Controller
    {
        
        // GET: WordController
        public ActionResult Index()
        {
            return View();
        }

        // GET: WordController/Details/5
        public ActionResult Details(string id)
        {
            id = id.Trim();
            if (string.IsNullOrWhiteSpace(id) || id.Length != 1)
            {
                return View();
            }

            if (!WordsHolder.Words.ContainsKey(id[0]))
            {
                return View();
            }

            var word = WordsHolder.Words[id[0]];

            return View(word);
        }

        public ActionResult BaiduLink([Bind(Prefix = "id")] string id)
        {
            var escaped = Uri.EscapeDataString(id);
            return Redirect(string.Concat("https://", $"hanyu.baidu.com/zici/s?wd={escaped}&query={escaped}"));
        }


        // GET: WordController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: WordController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: WordController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: WordController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: WordController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: WordController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

CharacterLookupMVC/Views/Word/Details.cshtml
@model CharacterLookupMVC.Models.Word

@{
    ViewData["Title"] = "Details";
}

<div>
    @{
        if (Model == null)
        {
            <dl class="row">
                <dt>貌似超纲了，小学字库未找到此字</dt>
            </dl>
        }
        else
        {
            <h4>生字详情</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Character)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Character)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Grade)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.GradeStr)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Semister)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.SemisterStr)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Article)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Article)
                </dd>
            </dl>
        }
    }
</div>
<div>
    <hr />
    @using (Html.BeginForm("Details","Word",FormMethod.Get,new {@class= "form-inline" }))
    {
        <div class="row">
            <div class="col-sm-12">
                <div style="padding-right: 5px; display:inline;">继续查询:</div><input type="text" name="id" class="box-shadow--4dp" placeholder="例" />
                <input type="submit" class="btn-default box-shadow--4dp" value="查询" />
            </div>
        </div>
    }
</div>
<div>
    <hr />
    @*@Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a> |*@
    @{
        if (Model != null)
        {
            @Html.ActionLink("百度汉语", "BaiduLink", new { id = Model.Character }, new { target = "_blank" })  <span> | </span>
        }
    }
    <a asp-controller="Home" asp-action="Index">主页</a>
</div>